apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent.fullname" . }}-workspace
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass | default "mayastor" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "5Gi" }}
