{{- if .Values.narrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}-narrator
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: narrator
spec:
  type: ClusterIP
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.narrator.musetalk.enabled }}
    - name: narr-muse
      port: {{ .Values.narrator.musetalk.port }}
      targetPort: narr-muse
      protocol: TCP
    {{- end }}
    {{- if .Values.narrator.hunyuan.enabled }}
    - name: narr-huny
      port: {{ .Values.narrator.hunyuan.port }}
      targetPort: narr-huny
      protocol: TCP
    {{- end }}
{{- end }}
