apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: {{ include "cto.namespace" . }}
  labels:
    {{- include "cto.controller.labels" . | nindent 4 }}
data:
  KUBERNETES_NAMESPACE: {{ include "cto.namespace" . | quote }}
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: {{ .Values.controller.service.port | quote }}
  RUST_LOG: "info,controller=debug"
  TEMPLATES_VERSION: {{ .Values.controller.templateVersion | quote }}
