apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cto.controller.fullname" . }}
  namespace: {{ include "cto.namespace" . }}
  labels:
    {{- include "cto.controller.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
{{- if .Values.tools.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cto.tools.fullname" . }}
  namespace: {{ include "cto.namespace" . }}
  labels:
    {{- include "cto.tools.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
