{{- if .Values.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-loki
  namespace: {{ include "observability.namespace" . }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
  {{- with .Values.loki.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - name: http
      port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.loki.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
{{- end }}
